apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chwnet-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  
  rules:
  - host: camptonhillsweather.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chwnet
            port:
              number: 80
